import { Globe, Mic } from "lucide-react";
import React from "react";
import { BrandIcon } from "./BrandIcon";

export const platforms = [
  {
    id: "youtube",
    name: "YouTube",
    icon: (props: any) => React.createElement(BrandIcon, { name: "youtube", ...props }),
    colorClass: "platform-youtube",
    bgGradient: "from-red-500/20 to-red-600/10",
    connected: true,
    username: "@NovusExchange",
    url: "https://www.youtube.com/@NovusExchange",
    followers: 125000,
    followersDisplay: "125K",
    posts: 342,
    lastSync: "2 min ago",
    status: "active",
    stats: { views: "2.5M", engagement: "8.2%", shares: "12.4K" },
    weeklyGrowth: 3.2,
    topPost: { likes: 15600, comments: 1240, title: "How to Go Viral in 2024" },
    weeklyData: [
      { day: "Mon", followers: 123000, views: 45000 },
      { day: "Tue", followers: 123400, views: 52000 },
      { day: "Wed", followers: 123800, views: 48000 },
      { day: "Thu", followers: 124200, views: 61000 },
      { day: "Fri", followers: 124600, views: 58000 },
      { day: "Sat", followers: 124800, views: 72000 },
      { day: "Sun", followers: 125000, views: 68000 },
    ],
    schedule: { pending: 5, published: 23 },
  },
  {
    id: "twitter",
    name: "X",
    icon: (props: any) => React.createElement(BrandIcon, { name: "twitter", ...props }),
    colorClass: "platform-twitter",
    bgGradient: "from-zinc-700/20 to-zinc-800/10",
    connected: true,
    username: "@NovusExchange",
    url: "https://x.com/NovusExchange",
    followers: 52000,
    followersDisplay: "52K",
    posts: 1289,
    lastSync: "1 min ago",
    status: "active",
    stats: { views: "1.8M", engagement: "4.5%", shares: "28.3K" },
    weeklyGrowth: 2.8,
    topPost: { likes: 8900, comments: 432, title: "Thread: 10 Tips for Growth" },
    weeklyData: [
      { day: "Mon", followers: 50200, views: 65000 },
      { day: "Tue", followers: 50600, views: 72000 },
      { day: "Wed", followers: 50900, views: 68000 },
      { day: "Thu", followers: 51200, views: 85000 },
      { day: "Fri", followers: 51500, views: 92000 },
      { day: "Sat", followers: 51800, views: 78000 },
      { day: "Sun", followers: 52000, views: 71000 },
    ],
    schedule: { pending: 12, published: 156 },
  },
  {
    id: "website",
    name: "Website",
    icon: Globe,
    colorClass: "platform-website",
    bgGradient: "from-teal-500/20 to-cyan-600/10",
    connected: true,
    username: "novusexchange.com",
    url: "https://novusexchange.com",
    followers: 39730,
    followersDisplay: "39.7K",
    posts: 234,
    lastSync: "5 min ago",
    status: "active",
    stats: { views: "890K", engagement: "3.2%", shares: "5.6K" },
    weeklyGrowth: 4.1,
    topPost: { likes: 2340, comments: 189, title: "Ultimate Guide to Content" },
    weeklyData: [
      { day: "Mon", followers: 38200, views: 32000 },
      { day: "Tue", followers: 38500, views: 35000 },
      { day: "Wed", followers: 38800, views: 38000 },
      { day: "Thu", followers: 39100, views: 42000 },
      { day: "Fri", followers: 39400, views: 45000 },
      { day: "Sat", followers: 39600, views: 48000 },
      { day: "Sun", followers: 39730, views: 52000 },
    ],
    schedule: { pending: 4, published: 52 },
    subPlatforms: ["Blog Posts", "Newsletter"],
  },
  {
    id: "podcast",
    name: "Podcast",
    icon: Mic,
    colorClass: "platform-podcast",
    bgGradient: "from-purple-500/20 to-violet-600/10",
    connected: true,
    username: "The Creator Show",
    followers: 18500,
    followersDisplay: "18.5K",
    posts: 89,
    lastSync: "30 min ago",
    status: "active",
    stats: { views: "456K", engagement: "15.2%", shares: "8.9K" },
    weeklyGrowth: 6.3,
    topPost: { likes: 3200, comments: 287, title: "Episode 89: Future of Content" },
    weeklyData: [
      { day: "Mon", followers: 17200, views: 18000 },
      { day: "Tue", followers: 17400, views: 21000 },
      { day: "Wed", followers: 17600, views: 19000 },
      { day: "Thu", followers: 17900, views: 24000 },
      { day: "Fri", followers: 18100, views: 28000 },
      { day: "Sat", followers: 18300, views: 32000 },
      { day: "Sun", followers: 18500, views: 35000 },
    ],
    schedule: { pending: 2, published: 89 },
  },
  {
    id: "rumble",
    name: "Rumble",
    icon: (props: any) => React.createElement(BrandIcon, { name: "rumble", ...props }),
    colorClass: "platform-rumble",
    bgGradient: "from-green-500/20 to-lime-600/10",
    connected: true,
    username: "@usinconstext",
    url: "https://rumble.com/user/usinconstext",
    followers: 12400,
    followersDisplay: "12.4K",
    posts: 89,
    lastSync: "Just now",
    status: "active",
    stats: { views: "145K", engagement: "8.2%", shares: "1.2K" },
    weeklyGrowth: 12.5,
    topPost: { likes: 1200, comments: 340, title: "The Truth About AI" },
    weeklyData: [
      { day: "Mon", followers: 11000, views: 15000 },
      { day: "Tue", followers: 11200, views: 18000 },
      { day: "Wed", followers: 11500, views: 22000 },
      { day: "Thu", followers: 11800, views: 25000 },
      { day: "Fri", followers: 12000, views: 28000 },
      { day: "Sat", followers: 12200, views: 30000 },
      { day: "Sun", followers: 12400, views: 35000 },
    ],
    schedule: { pending: 1, published: 23 },
  },
  {
    id: "tiktok",
    name: "TikTok",
    icon: (props: any) => React.createElement(BrandIcon, { name: "tiktok", ...props }),
    colorClass: "platform-tiktok",
    bgGradient: "from-pink-500/20 via-purple-500/10 to-cyan-500/10",
    connected: true,
    username: "@marcioeditions",
    url: "https://www.tiktok.com/@marcioeditions",
    followers: 89000,
    followersDisplay: "89K",
    posts: 156,
    lastSync: "5 min ago",
    status: "active",
    stats: { views: "5.1M", engagement: "12.4%", shares: "45.2K" },
    weeklyGrowth: 5.8,
    topPost: { likes: 45200, comments: 3100, title: "Viral Dance Challenge" },
    weeklyData: [
      { day: "Mon", followers: 85000, views: 120000 },
      { day: "Tue", followers: 85800, views: 145000 },
      { day: "Wed", followers: 86500, views: 132000 },
      { day: "Thu", followers: 87200, views: 189000 },
      { day: "Fri", followers: 87800, views: 210000 },
      { day: "Sat", followers: 88400, views: 245000 },
      { day: "Sun", followers: 89000, views: 198000 },
    ],
    schedule: { pending: 8, published: 45 },
  },
  {
    id: "instagram",
    name: "Instagram",
    icon: (props: any) => React.createElement(BrandIcon, { name: "instagram", ...props }),
    colorClass: "platform-instagram",
    bgGradient: "from-purple-500/20 via-pink-500/10 to-orange-400/10",
    connected: true,
    username: "@novusexchange",
    url: "https://www.instagram.com/novusexchange/",
    followers: 67000,
    followersDisplay: "67K",
    posts: 289,
    lastSync: "10 min ago",
    status: "active",
    stats: { views: "890K", engagement: "6.8%", shares: "8.9K" },
    weeklyGrowth: 2.1,
    topPost: { likes: 8900, comments: 456, title: "Behind the Scenes" },
    weeklyData: [
      { day: "Mon", followers: 65500, views: 28000 },
      { day: "Tue", followers: 65800, views: 32000 },
      { day: "Wed", followers: 66100, views: 29000 },
      { day: "Thu", followers: 66400, views: 35000 },
      { day: "Fri", followers: 66700, views: 38000 },
      { day: "Sat", followers: 66850, views: 42000 },
      { day: "Sun", followers: 67000, views: 39000 },
    ],
    schedule: { pending: 3, published: 18 },
  },
  {
    id: "facebook",
    name: "Facebook",
    icon: (props: any) => React.createElement(BrandIcon, { name: "facebook", ...props }),
    colorClass: "platform-facebook",
    bgGradient: "from-blue-600/20 to-blue-700/10",
    connected: true,
    username: "Novus Exchange",
    followers: 45000,
    followersDisplay: "45K",
    posts: 178,
    lastSync: "15 min ago",
    status: "active",
    stats: { views: "320K", engagement: "4.2%", shares: "2.1K" },
    weeklyGrowth: -0.5,
    topPost: { likes: 2300, comments: 189, title: "Community Update" },
    weeklyData: [
      { day: "Mon", followers: 45200, views: 12000 },
      { day: "Tue", followers: 45150, views: 11000 },
      { day: "Wed", followers: 45100, views: 10500 },
      { day: "Thu", followers: 45050, views: 11200 },
      { day: "Fri", followers: 45020, views: 10800 },
      { day: "Sat", followers: 45010, views: 9500 },
      { day: "Sun", followers: 45000, views: 9200 },
    ],
    schedule: { pending: 2, published: 12 },
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    icon: (props: any) => React.createElement(BrandIcon, { name: "linkedin", ...props }),
    colorClass: "platform-linkedin",
    bgGradient: "from-blue-700/20 to-blue-800/10",
    connected: true,
    username: "Novus Exchange",
    followers: 12000,
    followersDisplay: "12K",
    posts: 67,
    lastSync: "1 hour ago",
    status: "active",
    stats: { views: "156K", engagement: "5.1%", shares: "3.2K" },
    weeklyGrowth: 4.2,
    topPost: { likes: 890, comments: 67, title: "Industry Insights" },
    weeklyData: [
      { day: "Mon", followers: 11600, views: 5200 },
      { day: "Tue", followers: 11700, views: 5800 },
      { day: "Wed", followers: 11750, views: 6100 },
      { day: "Thu", followers: 11820, views: 7200 },
      { day: "Fri", followers: 11900, views: 6800 },
      { day: "Sat", followers: 11950, views: 4500 },
      { day: "Sun", followers: 12000, views: 4200 },
    ],
    schedule: { pending: 1, published: 8 },
  },
];

export const totalStats = {
  totalFollowers: "448K",
  totalViews: "12.1M",
  avgEngagement: "7.5%",
  connectedPlatforms: 8,
  totalPosts: 2644,
  weeklyGrowth: 3.62,
  totalShares: "114.5K",
  scheduledPosts: 37,
};

export const recentActivity = [
  { platform: "Podcast", icon: (props: any) => React.createElement(BrandIcon, { name: "podcast", ...props }), action: "Episode trending", detail: "Top 10 in Tech category", time: "1 hour ago", positive: true, type: "milestone" },
  { platform: "X", icon: (props: any) => React.createElement(BrandIcon, { name: "twitter", ...props }), action: "Thread went viral", detail: "2.3K retweets in 6 hours", time: "2 hours ago", positive: true, type: "milestone" },
  { platform: "Novus Exchange", icon: (props: any) => React.createElement(BrandIcon, { name: "website", ...props }), action: "Newsletter spike", detail: "1,200 new subscribers", time: "4 hours ago", positive: true, type: "engagement" },
  { platform: "TikTok", icon: (props: any) => React.createElement(BrandIcon, { name: "tiktok", ...props }), action: "Video went viral", detail: "45K+ likes in 24 hours", time: "6 hours ago", positive: true, type: "milestone" },
  { platform: "YouTube", icon: (props: any) => React.createElement(BrandIcon, { name: "youtube", ...props }), action: "New milestone", detail: "Reached 125K subscribers", time: "12 hours ago", positive: true, type: "milestone" },
  { platform: "Instagram", icon: (props: any) => React.createElement(BrandIcon, { name: "instagram", ...props }), action: "Story engagement spike", detail: "2,400 interactions", time: "1 day ago", positive: true, type: "engagement" },
  { platform: "Facebook", icon: (props: any) => React.createElement(BrandIcon, { name: "facebook", ...props }), action: "Reach decreased", detail: "-5% compared to last week", time: "2 days ago", positive: false, type: "alert" },
  { platform: "LinkedIn", icon: (props: any) => React.createElement(BrandIcon, { name: "linkedin", ...props }), action: "Article featured", detail: "Added to LinkedIn News", time: "3 days ago", positive: true, type: "feature" },
];

export const availablePlatforms = [
  { id: "pinterest", name: "Pinterest", icon: (props: any) => React.createElement(BrandIcon, { name: "pinterest", ...props }), description: "Visual discovery and bookmarking", users: "450M+" },
  { id: "snapchat", name: "Snapchat", icon: (props: any) => React.createElement(BrandIcon, { name: "snapchat", ...props }), description: "Stories and AR content", users: "750M+" },
  { id: "threads", name: "Threads", icon: (props: any) => React.createElement(BrandIcon, { name: "threads", ...props }), description: "Text-based conversations", users: "150M+" },
];

export const overallPerformance = [
  { name: "Week 1", followers: 310000, views: 7200000, engagement: 6.8 },
  { name: "Week 2", followers: 318000, views: 7800000, engagement: 7.0 },
  { name: "Week 3", followers: 325000, views: 8200000, engagement: 7.1 },
  { name: "Week 4", followers: 338000, views: 8900000, engagement: 7.3 },
];

export const platformColors: Record<string, string> = {
  youtube: "hsl(var(--youtube))",
  tiktok: "hsl(var(--tiktok))",
  instagram: "hsl(var(--instagram))",
  facebook: "hsl(var(--facebook))",
  linkedin: "hsl(var(--linkedin))",
  twitter: "hsl(var(--twitter))",
  website: "hsl(var(--website))",
  novusexchange: "hsl(var(--website))",
  podcast: "hsl(var(--podcast))", 
};
